
const Api =[{
    id:1,
    Name:"NODDLES",
    catagory:"Morning",
    pic:"images/ramen.png",   
    description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Non magnam, saepe quisquam expedita magni animi ratione libero quod ea minus ut corrupti, assumenda itaque voluptatum perferendis excepturi cumque placeat.",
},
{   id:2,
    Name:"BANANA",
    catagory:"Morning",
    pic:"images/Banana.svg",   
    description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Non magnam, saepe quisquam expedita magni animi ratione libero quod ea minus ut corrupti, assumenda itaque voluptatum perferendis excepturi cumque placeat.",
},
{   id:3,
    Name:"BAHUBALI THALI",
    catagory:"Lunch",
    pic:"images/thali.svg",   
    description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Non magnam, saepe quisquam expedita magni animi ratione libero quod ea minus ut corrupti, assumenda itaque voluptatum perferendis excepturi cumque placeat.",
},
{   id:4,
    Name:"CHOCOLATE ICE-CREAM",
    catagory:"Lunch",
    pic:"images/icecream.svg",   
    description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Non magnam, saepe quisquam expedita magni animi ratione libero quod ea minus ut corrupti, assumenda itaque voluptatum perferendis excepturi cumque placeat.",
},
{   id:5,
    Name:"CORN",
    catagory:"Evening",
    pic:"images/corn.svg",   
    description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Non magnam, saepe quisquam expedita magni animi ratione libero quod ea minus ut corrupti, assumenda itaque voluptatum perferendis excepturi cumque placeat.",
},
{   id:6,
    Name:" THALI",
    catagory:"Dinner",
    pic:"images/thali.svg",   
    description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Non magnam, saepe quisquam expedita magni animi ratione libero quod ea minus ut corrupti, assumenda itaque voluptatum perferendis excepturi cumque placeat.",
},

]
export default Api